### ISSUE TITLE
WARNING: Opening secrets file /etc/smokeping/smokeping_secrets: Permission denied

### ISSUE THREAD

**Issue by tanpengsccd** [dgraziotin/docker-smokeping-slave#1]
```
version: "2.1"
services:
    smokeping-slave:
        image: "dgraziotin/smokeping-slave"
        container_name: smokeping-slave
        hostname: slave.xxx.work
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
            - ServerName="SlaveSMP"
            - SHARED_SECRET="passwd123"
            - MASTER_URL=http://master.xxx.work:8888/smokeping/smokeping.cgi
        # volumes:
        #   - /data/smokeping/config:/config
        #   - /data/smokeping/data:/data
        #    - /data/smokeping/smokeping:/etc/smokeping
        ports:
            - 8888:80
        restart: unless-stopped
```

```docker-compose up```  get error: WARNING: Opening secrets file /etc/smokeping/smokeping_secrets: Permission denied

**Comment by tanpengsccd** [comment]
``` docker exec -it smokeping-slave bash```
```
root@tccd:/# smokeping --check
ERROR: can't open /usr/bin/../etc/smokeping/config: No such file or directory
root@tccd:/# 
```

**Comment by dgraziotin** [comment]
I can't replicate your first issue with this docker-compose.yml (with real URL, hostname, and secrets):

```
---
version: "2.1"
services:
  smokeping-slave:
    image: dgraziotin/smokeping-slave
    container_name: smokeping-slave
    hostname: my-slave
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SHARED_SECRET=12345
      - MASTER_URL=http://my-master.ext/smokeping/smokeping.cgi
        #    volumes:
        #- ./config:/config
        #- ./data:/data
    restart: unless-stopped
```

```
docker-compose up | grep WARNING
Creating network "smokeping_default" with the default driver
Creating smokeping-slave ... done
```

```
docker exec -it smokeping-slave ls -la /config/smokeping_secrets
-rw-r----- 1 abc abc 25 Jul  6 10:17 /config/smokeping_secrets
```

I do see the error message you have in the second comment, but it does not seem related or even an issue at all. Probably what a slave instance shows. It is otherwise working with me.

Are you using the latest image?
