### ISSUE TITLE
exec /init: exec format error

### ISSUE THREAD

**Issue by Valdri** [dgraziotin/docker-smokeping-slave#3]
my compose file:
```
version: "2.1"
services:
  smokeping-slave:
    image: dgraziotin/smokeping-slave
    container_name: smokeping-slave
    hostname: wan2
    entrypoint: /init
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - 'SHARED_SECRET=XXXXXXX'
      - 'MASTER_URL=http://192.168.0.168:8081/smokeping/smokeping.cgi'

    restart: unless-stopped
    ```
System info:
Docker version 26.0.0, build 2ae903e
Host: Debian GNU/Linux 11 (bullseye)
